steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/random-game-picker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/random-game-picker']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        # Use user-defined substitutions (cloud build requires the leading underscore
        # in the substitution name when passed on the command line). Reference them
        # here as ${_SERVICE_NAME} and ${_REGION}.
        SERVICE_NAME=${_SERVICE_NAME}
        REGION=${_REGION}
        if [ -z "$SERVICE_NAME" ] || [ -z "$REGION" ]; then
          echo "ERROR: _SERVICE_NAME and _REGION substitutions must be provided."
          exit 1
        fi
        gcloud run deploy "$SERVICE_NAME" \
          --image "gcr.io/$PROJECT_ID/random-game-picker" \
          --region "$REGION" \
          --platform managed \
          --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/random-game-picker'
substitutions:
  _SERVICE_NAME: "game-picker"
  _REGION: "us-central1"
# Usage:
# gcloud builds submit --config=cloudbuild.yaml --substitutions _SERVICE_NAME=game-picker,_REGION=us-central1
# Make sure to set the PROJECT_ID in gcloud (gcloud config set project PROJECT_ID)
