steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/random-game-picker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/random-game-picker']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud run deploy "$SERVICE_NAME" \
          --image "gcr.io/$PROJECT_ID/random-game-picker" \
          --region "$REGION" \
          --platform managed \
          --allow-unauthenticated

  # Write a deployment entry to Cloud Logging so there is an explicit record
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        LOG_NAME="random-game-picker-deploy"
        MESSAGE="Deployed $SERVICE_NAME to $REGION in project $PROJECT_ID"
        # Write a simple structured log entry to Cloud Logging. The Cloud Build
        # service account will need the Logging Writer role (roles/logging.logWriter).
        gcloud logging write "$LOG_NAME" "$MESSAGE" --severity=INFO --project="$PROJECT_ID"
    options:
    logging: CLOUD_LOGGING_ONLY
# Usage:
# gcloud builds submit --config=cloudbuild.yaml --substitutions _SERVICE_NAME=game-picker,_REGION=us-central1
# Make sure to set the PROJECT_ID in gcloud (gcloud config set project PROJECT_ID)
