steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/random-game-picker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/random-game-picker']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud run deploy "$SERVICE_NAME" \
          --image "gcr.io/$PROJECT_ID/random-game-picker" \
          --region "$REGION" \
          --platform managed \
          --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
# Usage:
# gcloud builds submit --config=cloudbuild.yaml --substitutions _SERVICE_NAME=game-picker,_REGION=us-central1
# Make sure to set the PROJECT_ID in gcloud (gcloud config set project PROJECT_ID)
